name: Terraform Apply

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      solutionModule:
        description: 'Solution Module'
        type: choice
        options:
        - 0.Global.Foundation
        - 1.Virtual.Network
        - 2.Artificial.Intelligence
        - 3.Image.Builder
        - 4.Storage
        - 5.Storage.Cache
        - 6.Render.Manager
        - 7.Render.Farm
        - 8.Artist.Workstation
        required: true
      logLevel:
        description: 'Log Level'
        type: choice
        options:
        - Error
        - Warn
        - Info
        - Debug
        - Trace
        required: true
      destroyMode:
        description: 'Destroy Mode'
        type: boolean
        required: false

env:
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  TF_LOG: ${{github.event.inputs.logLevel}}

permissions:
  contents: read
  pull-requests: write

jobs:
  terraformApply:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - if: github.event_name == 'pull_request'
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | gh auth login --with-token
          solutionModule=$(gh pr view ${{github.event.pull_request.number}} --json files)
          solutionModule=$(echo $solutionModule | jq -r .files[].path)
          readarray -d / -t solutionModule <<< $solutionModule
          echo "solutionModule=$solutionModule" >> $GITHUB_ENV

      - if: github.event_name != 'pull_request'
        run: |
          solutionModule=${{github.event.inputs.solutionModule}}
          echo "solutionModule=$solutionModule" >> $GITHUB_ENV

      - if: startsWith(env.solutionModule, 4)
        run: |
          latestVersion=$(curl -s https://api.github.com/repos/Azure/Avere/releases/latest | jq -r .tag_name)
          downloadUrl=https://github.com/Azure/Avere/releases/download/$latestVersion/terraform-provider-avere
          localDirectory=~/.terraform.d/plugins/registry.terraform.io/hashicorp/avere/${latestVersion:1}/linux_amd64
          mkdir -p $localDirectory
          curl -o $localDirectory/terraform-provider-avere_$latestVersion -L $downloadUrl
          chmod 755 $localDirectory/terraform-provider-avere_$latestVersion

      - if: startsWith(env.solutionModule, 1)
        run: terraform -chdir=$(pwd)/${{env.solutionModule}} init -upgrade

      - if: "!startsWith(env.solutionModule, 1)"
        run: terraform -chdir=$(pwd)/${{env.solutionModule}} init -upgrade -backend-config ../0.Global.Foundation/backend.config

      - id: apply
        if: github.event_name == 'pull_request'
        run: |
         tfPlan=$(pwd)/${{env.solutionModule}}/terraform.plan
         terraform -chdir=$(pwd)/${{env.solutionModule}} apply -auto-approve -no-color $tfPlan

      - if: github.event_name != 'pull_request' && github.event.inputs.destroyMode != 'true'
        run: terraform -chdir=$(pwd)/${{env.solutionModule}} apply -auto-approve

      - if: github.event_name != 'pull_request' && github.event.inputs.destroyMode == 'true'
        run: terraform -chdir=$(pwd)/${{env.solutionModule}} apply -auto-approve -destroy

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Terraform Apply (${{env.solutionModule}})\n\n${{steps.apply.outputs.stdout}}`
            })
