#cloud-config
packages:
- jq
- unzip

final_message: "<> DONE: Cloud-Init COMPLETE. The VM is UP and READY ($UPTIME seconds elapsed)."

write_files:
  - encoding: b64
    path: /root/.ssh/id_rsa
    permissions: '0600'
    content: '<id_rsa>'

  - path: /opt/setup_environment.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export REGION='<region>'
      export RESOURCE_GROUP_NAME='<resource_group_name>'
      export CONTROLLER_IMAGE='<controller_image>'
      export VFXT_IMAGE='<vfxt_image>'
      export AVERE_ADMIN_PW='<avere_admin_pw>'
      export VNET_NAME='<vnet_name>'
      export TF_VFXT_CONFIG='<terraform_file_config>'

      apt-get update
      apt install azure-cli -y

      echo "wget terraform zip"
      wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      [ $? -ne 0 ] && error "wget terraform zip - setup step"

      echo "unzip terraform.zip"
      unzip terraform_0.15.0_linux_amd64.zip
      [ $? -ne 0 ] && error "unzip terraform.zip - setup step"

      echo "mv tf folder to /usr/local/bin"
      mv terraform /usr/local/bin
      [ $? -ne 0 ] && error "mv tf folder to /usr/local/bin - setup step"

      echo "chmod terraform executable to be globally runnable"
      chmod 755 /usr/local/bin/terraform
      [ $? -ne 0 ] && error "chmod terraform executable - setup step"

      echo "Get the version of Azure/Avere repo"
      re="[0-9]+\.[0-9]+\.[0-9]"
      version=$(curl -s https://api.github.com/repos/Azure/Avere/releases/latest | jq -r .tag_name | sed -e 's/[^0-9]*\([0-9].*\)$/\1/')
      [[ $version =~ $re ]] || error "Unexpected version format: $version"

      echo "browser_download"
      browser_download_url=$(curl -s https://api.github.com/repos/Azure/Avere/releases/latest | jq -r .assets[].browser_download_url | grep -e "terraform-provider-avere$")
      [ $? -ne 0 ] && error "browser_download_url for terraform-provider-avere - setup step"

      echo "mkdir terraform avere linux dir"
      mkdir -p ~/.terraform.d/plugins/registry.terraform.io/hashicorp/avere/$version/linux_amd64
      [ $? -ne 0 ] && error "mkdir terraform avere linux dir - setup step"

      echo "wget terraform-provider-avere"
      wget -O ~/.terraform.d/plugins/registry.terraform.io/hashicorp/avere/$version/linux_amd64/terraform-provider-avere_v$version $browser_download_url
      [ $? -ne 0 ] && error "wget terraform-provider-avere - setup step"

      echo "chmod terraform provider avere"
      chmod 755 ~/.terraform.d/plugins/registry.terraform.io/hashicorp/avere/$version/linux_amd64/terraform-provider-avere_v$version
      [ $? -ne 0 ] && error "chmod terraform provider avere - setup step"

      echo "mkdir tf && cd tf"
      mkdir tf && cd tf
      [ $? -ne 0 ] && error "mkdir tf && cd tf - setup step"

      echo "git init"
      git init
      [ $? -ne 0 ] && error "git init - setup step"

      echo "git remote"
      git remote add origin -f https://github.com/Azure/Avere.git
      [ $? -ne 0 ] && error "git remote cmd for Avere.git- setup step"

      echo "git config cmd for setup"
      git config core.sparsecheckout true
      [ $? -ne 0 ] && error "git config - setup step."

      echo "append src/terraform to /sparse-checkout"
      echo "src/terraform/*" >> .git/info/sparse-checkout
      [ $? -ne 0 ] && error "append src/terraform to /sparse-checkout - setup step"

      echo "git pull main branch"
      git pull origin main
      [ $? -ne 0 ] && error "git pull main branch - setup step"

      echo "cd to file path"
      cd src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      echo "Add comment to SSH public key"
      sshkey="<ssh_key> azureuser@linuxvm"
      [ $? -ne 0 ] && error "Add comment to sshkey."

      echo "sed command for initial main.tf setup"
      sed -i -E -e "s:vm_ssh_key_data = null:vm_ssh_key_data = \"${sshkey}\":" \
        -e "s/location\s*= \"eastus\"/location = \"${REGION}\"/" \
        -e "s/open_external_sources\s*= [\"*\"]/open_external_sources = [\"AzureCloud\"]/" \
        -e "s/controller_add_public_ip\s*= true/controller_add_public_ip = false/" \
        -e "s/controller_image_id\s*= null/controller_image_id = \"$CONTROLLER_IMAGE\"/" \
        -e "s/vfxt_image_id\s*= null/vfxt_image_id = \"$VFXT_IMAGE\"/" \
        -e "s/(([a-z]+)_resource_group_name)\s*= \"[^\"]+\"/\1 = \"${RESOURCE_GROUP_NAME}-\2\"/" \
        -e "s/vfxt_cluster_password\s*= \"VFXT_PASSWORD\"/vfxt_cluster_password = \"${AVERE_ADMIN_PW}\"/" \
        -e "s/peer_vnet_rg\s*= \"\"/peer_vnet_rg = \"$RESOURCE_GROUP_NAME\"/" \
        -e "s/peer_vnet_name\s*= \"\"/peer_vnet_name = \"$VNET_NAME\"/" \
        -e "s/storage_account_name\s*= \"storageaccount\"/storage_account_name = \"$RESOURCE_GROUP_NAME\"/" \
        -e 's/vfxt_node_count\s*= 3/vfxt_node_count = <original_node_count>/' main.tf

      [ $? -ne 0 ] && error "sed command for initial main.tf setup."

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform apply"
      terraform apply -auto-approve
      [ $? -ne 0 ] && error "terraform apply cmd for $TF_VFXT_CONFIG"

      echo "DONE: end of $0"

  - path: /opt/scaleup.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export TF_VFXT_CONFIG='<terraform_file_config>'

      echo "to file path for scaleup"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "to file path for scaleup"

      echo "sed command for node counts in scaleup"
      sed -i -E -e 's/vfxt_node_count\s*= <original_node_count>/vfxt_node_count = <new_node_count>/' main.tf
      [ $? -ne 0 ] && error "sed command for node counts in scaleup"

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform apply scaleup"
      terraform apply -auto-approve |& tee /tmp/scaleup.txt
      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform apply cmd for scaling up nodes"

      echo "DONE: end of $0"

  - path: /opt/scaledown.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export TF_VFXT_CONFIG='<terraform_file_config>'

      echo "cd to file path"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      echo "sed command for node counts in scale down"
      sed -i -E -e 's/vfxt_node_count\s*= <new_node_count>/vfxt_node_count = <original_node_count>/' main.tf
      [ $? -ne 0 ] && error "sed command for node counts in scale down"

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform apply scaledown"
      terraform apply -auto-approve |& tee /tmp/scaledown.txt
      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform apply cmd for scaling down nodes"

      echo "DONE: end of $0"

  - path: /opt/destroy.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export TF_VFXT_CONFIG='<terraform_file_config>'

      echo "cd to file path"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform destroy"
      terraform destroy -auto-approve |& tee /tmp/destroy.txt
      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform destroy cmd for $TF_VFXT_CONFIG"

      echo "DONE: end of $0"

  - path: /opt/vdbench_destroy.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export REGION='<region>'
      export RESOURCE_GROUP_NAME='<resource_group_name>'
      export TF_VFXT_CONFIG='<terraform_file_config>'
      export VDBENCH_URL='<vdbench_download_url>'

      echo " cd to file path"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      echo "tee outputs to json"
      terraform output -json |& tee /tmp/tf_output.json
      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform outputs"

      CONTROLLER_ADDRESS=$(jq -r ".controller_address.value" /tmp/tf_output.json)
      USERNAME=$(jq -r ".controller_username.value" /tmp/tf_output.json)
      VSERVER_IP_ADDRESSES=$(jq -c ".mount_addresses.value" /tmp/tf_output.json)
      NFS_EXPORT_PATH=$(jq -r ".mount_namespace_path.value" /tmp/tf_output.json)

      echo "Add comment to SSH public key"
      sshkey="<ssh_key> azureuser@linuxvm"
      [ $? -ne 0 ] && error "Add comment to sshkey."

      cd ../vdbench

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform destroy for vdbench"
      terraform destroy -auto-approve -var="location=${REGION}" \
        -var="vmss_resource_group_name=${RESOURCE_GROUP_NAME}-vmss" \
        -var="controller_address=${CONTROLLER_ADDRESS}" \
        -var="controller_username=${USERNAME}" \
        -var="ssh_key_data=${sshkey}" \
        -var="vserver_ip_addresses=${VSERVER_IP_ADDRESSES}" \
        -var="nfs_export_path=${NFS_EXPORT_PATH}" \
        -var="vdbench_url=${VDBENCH_URL}" \
        -var="vnet_resource_group=${RESOURCE_GROUP_NAME}-network" |& tee /tmp/vdbench_destroy.txt

      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform destroy cmd for vdbench"

      echo "DONE: end of $0"

  - path: /opt/vdbench_run.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export AZURE_SUBSCRIPTION='<sub_id>'
      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export REGION='<region>'
      export RESOURCE_GROUP_NAME='<resource_group_name>'
      export TF_VFXT_CONFIG='<terraform_file_config>'
      export VDBENCH_URL='<vdbench_download_url>'

      echo "cd to file path"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      CONTROLLER_ADDRESS=$(terraform output -json | jq -r ".controller_address.value")
      USERNAME=$(terraform output -json | jq -r ".controller_username.value")
      VSERVER_IP_ADDRESSES=$(terraform output -json | jq -c ".mount_addresses.value")
      NFS_EXPORT_PATH=$(terraform output -json | jq -r ".mount_namespace_path.value")

      echo "Add comment to SSH public key"
      sshkey="<ssh_key> azureuser@linuxvm"
      [ $? -ne 0 ] && error "Add comment to sshkey."

      cd ../vdbench

      echo "terraform init"
      terraform init
      [ $? -ne 0 ] && error "terraform init cmd"

      echo "terraform apply vdbench"
      terraform apply -auto-approve -var="location=${REGION}" \
        -var="vmss_resource_group_name=${RESOURCE_GROUP_NAME}-vmss" \
        -var="controller_address=${CONTROLLER_ADDRESS}" \
        -var="controller_username=${USERNAME}" \
        -var="ssh_key_data=${sshkey}" \
        -var="vserver_ip_addresses=${VSERVER_IP_ADDRESSES}" \
        -var="nfs_export_path=${NFS_EXPORT_PATH}" \
        -var="vdbench_url=${VDBENCH_URL}" \
        -var="vnet_resource_group=${RESOURCE_GROUP_NAME}-network" |& tee /tmp/vdbench_run.txt

      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform apply cmd for vdbench"

      echo "vdbench terraform outputs"
      IP_ADDRESS_COMMAND=$(terraform output -json | jq -r ".vmss_addresses_command.value") &&
      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID &&
      az account set -s $ARM_SUBSCRIPTION_ID &&
      IP_ADDRESS=$(${IP_ADDRESS_COMMAND} | jq -r '.[0]')
      [ $? -ne 0 ] && error "vdbench terraform outputs."

      echo "ssh - initial connection needed for below scp cmd"
      ssh -o "StrictHostKeyChecking=no" -oProxyCommand="ssh -oStrictHostKeyChecking=no -W %h:%p  ${USERNAME}@${CONTROLLER_ADDRESS}" ${USERNAME}@${IP_ADDRESS} ls
      echo "scp cmd to copy id_rsa "
      scp -o "ProxyJump ${USERNAME}@${CONTROLLER_ADDRESS}" /root/.ssh/id_rsa ${USERNAME}@${IP_ADDRESS}:.ssh/id_rsa
      [ $? -ne 0 ] && error "scp cmd to copy id_rsa"

      echo "ssh to run copy_idrsa.sh"
      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} /home/azureuser/copy_idrsa.sh
      [ $? -ne 0 ] && error "ssh to run copy_idrsa.sh"

      echo "ssh to run vdbench"
      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "tmux new-session -d \"/home/${USERNAME}/run_vdbench.sh <vdbench_config>.conf uniquestring1 >> /home/${USERNAME}/vdb.log 2>&1\""
      [ $? -ne 0 ] && error "ssh to run vdbench"

      echo "DONE: end of $0"

  - path: /opt/vdbench_save.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      function error() {
        >&2 echo "echo >< ERROR: $* See log for details."
        exit 1
      }

      export ARM_SUBSCRIPTION_ID='<sub_id>'
      export ARM_CLIENT_ID='<arm_client_id>'
      export ARM_CLIENT_SECRET='<arm_client_scrt>'
      export ARM_TENANT_ID='<arm_tenant_id>'
      export REGION='<region>'
      export RESOURCE_GROUP_NAME='<resource_group_name>'
      export TF_VFXT_CONFIG='<terraform_file_config>'

      echo " cd to file path"
      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"

      echo "tee outputs to json"
      terraform output -json |& tee /tmp/tf_output.json
      [ ${PIPESTATUS[0]} -ne 0 ] && error "terraform outputs"

      CONTROLLER_ADDRESS=$(jq -r ".controller_address.value" /tmp/tf_output.json)
      USERNAME=$(jq -r ".controller_username.value" /tmp/tf_output.json)
      VSERVER_IP_ADDRESSES=$(jq -c ".mount_addresses.value" /tmp/tf_output.json)
      NFS_EXPORT_PATH=$(jq -r ".mount_namespace_path.value" /tmp/tf_output.json)

      cd ../vdbench

      echo "vdbench terraform outputs"
      IP_ADDRESS_COMMAND=$(terraform output -json | jq -r ".vmss_addresses_command.value") &&
      IP_ADDRESS=$(${IP_ADDRESS_COMMAND} | jq -r '.[0]')
      [ $? -ne 0 ] && error "vdbench terraform outputs."

      echo "ssh - initial connection needed for below scp cmd"
      ssh -o "StrictHostKeyChecking=no" -oProxyCommand="ssh -oStrictHostKeyChecking=no -W %h:%p  ${USERNAME}@${CONTROLLER_ADDRESS}" ${USERNAME}@${IP_ADDRESS} ls
      [ $? -ne 0 ] && error "scp cmd to copy id_rsa"

      echo "ssh to cat vdbench log"
      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "cat /home/${USERNAME}/vdb.log" |& tee /tmp/vdbench_save.txt
      [ $? -ne 0 ] && error "ssh to cat vdbench.log"

      echo "DONE: end of $0"
runcmd:
  - "echo '# STEP: Setup SSH key.'"
  - "cp -v /root/.ssh/id_rsa /home/<vm_admin_user>/.ssh/id_rsa"
  - "/opt/setup_environment.sh"
