// Copyright (C) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE-CODE in the project root for license information.
package azure

const (
	AZURE_STORAGE_ACCOUNT     = "AZURE_STORAGE_ACCOUNT"
	AZURE_STORAGE_ACCOUNT_KEY = "AZURE_STORAGE_ACCOUNT_KEY"

	AZURE_EVENTHUB_SENDERKEYNAME = "AZURE_EVENTHUB_SENDERKEYNAME"
	AZURE_EVENTHUB_SENDERKEY     = "AZURE_EVENTHUB_SENDERKEY"
	AZURE_EVENTHUB_NAMESPACENAME = "AZURE_EVENTHUB_NAMESPACENAME"
)
