// Copyright (C) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE-CODE in the project root for license information.
package azure

import (
	"time"
)

const (
	AZURE_TENANT_ID       = "AZURE_TENANT_ID"
	AZURE_CLIENT_ID       = "AZURE_CLIENT_ID"
	AZURE_CLIENT_SECRET   = "AZURE_CLIENT_SECRET"
	AZURE_SUBSCRIPTION_ID = "AZURE_SUBSCRIPTION_ID"

	AZURE_STORAGE_ACCOUNT     = "AZURE_STORAGE_ACCOUNT"
	AZURE_STORAGE_ACCOUNT_KEY = "AZURE_STORAGE_ACCOUNT_KEY"

	AZURE_EVENTHUB_SENDERKEYNAME = "AZURE_EVENTHUB_SENDERKEYNAME"
	AZURE_EVENTHUB_SENDERKEY     = "AZURE_EVENTHUB_SENDERKEY"
	AZURE_EVENTHUB_NAMESPACENAME = "AZURE_EVENTHUB_NAMESPACENAME"

	DEFAULT_OPERATION_POLL_TIME = time.Duration(10) * time.Second
	MAX_OPERATION_POLL_TIME     = time.Duration(60) * time.Second
)
