unique_name="UNIQUENAME"
resource_group_name="UNIQUENAME-rg"
location="REGION"
ssh_key_data="SSHKEY"
virtual_network_resource_group="vnet-rg"
virtual_network_name="vnet-name"
virtual_network_subnet_name="vnet-subnet-name"