FROM centos:7.9.2009

ARG binDirectory="/usr/bin"

ARG storageContainerUrl="https://azrender.blob.core.windows.net/bin"
ARG storageContainerSas="?sv=2021-04-10&st=2022-01-01T08%3A00%3A00Z&se=2222-12-31T08%3A00%3A00Z&sr=c&sp=r&sig=Q10Ob58%2F4hVJFXfV8SxJNPbGOkzy%2BxEaTd5sJm8BLk8%3D"

ARG rendererPathBlender="$binDirectory/blender"

RUN echo "Customize (Start): Blender"
RUN yum -y install libxkbcommon
RUN yum -y install libXxf86vm
RUN yum -y install libXfixes
RUN yum -y install libXrender
RUN yum -y install libXi
RUN yum -y install libGL
ARG versionInfo="3.4.1"
ARG versionType="linux-x64"
ARG installFile="blender-$versionInfo-$versionType.tar.xz"
ARG downloadUrl="$storageContainerUrl/Blender/$versionInfo/$installFile$storageContainerSas"
RUN curl -o $installFile -L $downloadUrl
RUN tar -xJf $installFile
RUN mkdir -p $rendererPathBlender
RUN mv blender-$versionInfo-$versionType/* $rendererPathBlender
RUN echo "Customize (End): Blender"
